#!/bin/bash
cp manifest.json manifest.save.json
sed -i '/key/d' manifest.json
zip KiosqueAdb2Calendar.zip -r . -x ".git/*" -x "make_delivery" -x "manifest.save.json" -x "KiosqueAdb2Calendar.zip" -x "bower.json"
mv manifest.save.json manifest.json
